backend:
  name: github
  repo: thiagopaixao/teste_astro_leaflet
  branch: main

media_folder: 'public/uploads'
public_folder: '/uploads'

local_backend: true

imports:
  - ./components/Group.yml
  - ./components/Cta.yml
  - ./components/Text.yml
  - ./components/VideoEmbed.yml
  - ./components/ImageBlock.yml
  - ./components/ChartBar.yml
  - ./components/Column.yml
  - ./components/ColumnSticky.yml
