backend:
  name: github
  repo: thiagopaixao/teste_astro_leaflet
  branch: main

media_folder: 'public/uploads'
public_folder: '/uploads'

local_backend: true

imports:
  - ./components/Group.yml
  - ./components/Column.yml
  - ./components/ColumnSticky.yml
  - ./components/CardsCall.yml
  - ./components/LogosGroup.yml
  - ./components/ChartBar.yml
  - ./components/VideoEmbed.yml
  - ./components/Text.yml
  - ./components/InnerColumns.yml
  - ./components/ImageBlock.yml

collections:
  - name: 'pages'
    label: 'Páginas'
    folder: 'src/content/pages'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Título', name: 'title', widget: 'string', required: false }
      - label: 'Componentes'
        name: 'components'
        widget: 'list'
        collapsed: true
        required: false
        types:
          - *group
          - *cta
