components:
  cards_call: &cards-call
    label: 'Cards Call'
    name: 'cardsCall'
    widget: 'object'
    collapsed: true
    summary: 'Cards Call'
    fields:
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'CardsCall' }
      - label: 'Cards'
        name: 'cardsCallArr'
        widget: 'list'
        fields:
          - label: 'Link'
            name: 'link'
            widget: 'object'
            fields:
              - { label: 'URL', name: 'url', widget: 'string' }
          - label: 'Imagem'
            name: 'img'
            widget: 'object'
            fields:
              - { label: 'Imagem', name: 'src', widget: 'image' }
          - { label: 'Título', name: 'title', widget: 'string' }
          - { label: 'Texto', name: 'text', widget: 'text' }
