components:
  chart_bar: &chart-bar
    label: 'Chart Bar'
    name: 'chartBar'
    widget: 'object'
    collapsed: true
    summary: 'Chart Bar'
    fields:
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'ChartBar' }
      - { label: 'Título do Gráfico', name: 'chartTitle', widget: 'string' }
      - { label: 'Notas do Gráfico', name: 'chartNotes', widget: 'text' }
      - label: 'Barras'
        name: 'chartBars'
        widget: 'list'
        fields:
          - { label: 'Cor', name: 'color', widget: 'color' }
          - { label: 'Número', name: 'number', widget: 'number' }
          - { label: 'Porcentagem', name: 'numberPercent', widget: 'number' }
          - { label: 'Rótulo', name: 'label', widget: 'string' }
