chartPercentage: &chartPercentage
  label: 'Chart Percentage'
  name: 'ChartPercentage'
  widget: 'object'
  summary: '{{fields.chartPercentageTitle}}'
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'ChartPercentage'
    - label: 'Chart Percentage Title'
      name: 'chartPercentageTitle'
      widget: 'string'
      required: false
    - label: 'Chart Notes'
      name: 'chartPercentageNotes'
      widget: 'string'
      required: false
    - label: 'Chart Percentage Bars'
      name: 'chartPercentageBars'
      widget: 'list'
      required: false
      fields:
        - label: 'Label'
          name: 'label'
          widget: 'string'
          required: true
        - label: 'Color'
          name: 'color'
          widget: 'color'
          required: false
          enableAlpha: true
          allowInput: true
        - label: 'Number'
          name: 'number'
          widget: 'number'
          required: true
label: Chart Percentage
name: chart-percentage
widget: object
fields:
  - {
      label: Título,
      name: chartTitle,
      widget: string,
      required: false,
    }
  - {
      label: Notas,
      name: chartNotes,
      widget: markdown,
      required: false,
    }
  - {
      label: Valores,
      name: chartValues,
      widget: list,
      fields:
        [
          { label: Cor, name: color, widget: color },
          {
            label: Valor,
            name: number,
            widget: number,
            min: 0,
            max: 100,
          },
          { label: Rótulo, name: label, widget: string },
        ],
    }
