components:
  column_sticky: &column-sticky
    label: 'Column Sticky'
    name: 'columnSticky'
    widget: 'object'
    collapsed: true
    summary: 'Column Sticky'
    fields:
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'ColumnSticky' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Corpo', name: 'body', widget: 'string', required: false }
      - {
          label: 'Cor do Texto',
          name: 'txtColor',
          widget: 'color',
          required: false,
          enableAlpha: true,
        }
      - {
          label: 'Cor de Fundo',
          name: 'bgColor',
          widget: 'color',
          required: false,
          enableAlpha: true,
        }
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'select',
          options: ['default', 'text-bigger'],
          default: 'default',
        }
      - {
          label: 'Padding Superior',
          name: 'paddingTop',
          widget: 'boolean',
          required: false,
        }
      - {
          label: 'Padding Inferior',
          name: 'paddingBottom',
          widget: 'boolean',
          required: false,
        }
      - label: 'Componentes'
        name: 'components'
        widget: 'list'
        collapsed: true
        types:
          - <<: *text
