components:
  column: &column
    label: 'Column'
    name: 'column'
    widget: 'object'
    collapsed: true
    summary: 'Column'
    fields:
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'Column' }
      - label: 'Componentes'
        name: 'components'
        widget: 'list'
        collapsed: true
        types:
          - <<: *logos-group
          - <<: *chart-bar
          - <<: *video-embed
          - <<: *text
          - <<: *inner-columns
          - <<: *image-block
