label: Coluna
name: column
widget: object
fields:
  - {
      label: 'Padding Top',
      name: paddingTop,
      widget: boolean,
      default: false,
    }
  - {
      label: 'Padding Bottom',
      name: paddingBottom,
      widget: boolean,
      default: false,
    }
  - {
      label: 'Componentes',
      name: components,
      widget: list,
      fields:
        - {
            label: 'Componente',
            name: component,
            widget: relation,
            collection: components,
            searchFields: ['label'],
            displayFields: ['label'],
            valueField: '{{name}}',
          },
    }
