include: &include
  label: 'Include'
  name: 'Include'
  widget: 'object'
  summary: '{{fields.slug}}'
  collapsed: true
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'Include'
      collapsed: true
    - label: 'Target page slug'
      name: 'slug'
      widget: 'relation'
      collection: 'pages'
      value_field: '{{slug}}'
      search_fields: ['title', 'slug']
      display_fields: ['title', 'slug']
      required: false
      hint: 'Select the page whose content will be included here.'
      filters:
        - field: slug
          values: ['{{slug}}']
          exclude: true
      collapsed: true
