include: &include
  label: 'Include'
  name: 'Include'
  widget: 'object'
  summary: '{{fields.slug}}'
  collapsed: true
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'Include'
      collapsed: true
    - label: 'Target page slug'
      name: 'slug'
      widget: 'string'
      required: false
      hint: 'Type the slug of the page whose content will be included here (the slug field of that page, not the file name).'
      collapsed: true
