innerColumns: &innerColumns
  label: 'Inner Columns'
  name: 'InnerColumns'
  widget: 'object'
  summary: 'Inner Columns'
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'InnerColumns'
    - label: 'Column 1'
      name: 'column1'
      widget: 'list'
      required: false
      types:
        - *text
        - *chartBar
        - *imageBlock
        - *videoEmbed
        - *logosGroup
        - *innerColumns
    - label: 'Column 2'
      name: 'column2'
      widget: 'list'
      required: false
      types:
        - *text
        - *chartBar
        - *imageBlock
        - *videoEmbed
        - *logosGroup
        - *innerColumns
