label: 'Map'
name: 'Map'
widget: 'object'
summary: '{{fields.mapView}}'
fields:
  - label: 'Type'
    name: 'type'
    widget: 'hidden'
    default: 'Map'
  - label: 'Column Align'
    name: 'columnAlign'
    widget: 'select'
    options: ['left', 'right', 'center']
    default: 'left'
    required: false
  - label: 'Floating Text'
    name: 'floatingText'
    widget: 'boolean'
    required: false
    default: false
  - label: 'Text Color'
    name: 'txtColor'
    widget: 'color'
    required: false
    enableAlpha: true
    allowInput: true
  - label: 'Background Color'
    name: 'bgColor'
    widget: 'color'
    required: false
    enableAlpha: true
    allowInput: true
  - label: 'Map View'
    name: 'mapView'
    widget: 'string'
    required: false
  - label: 'Components'
    name: 'components'
    widget: 'list'
    required: false
    types:
      - label: 'Text'
        name: 'Text'
        widget: 'object'
        fields:
          - label: 'Type'
            name: 'type'
            widget: 'hidden'
            default: 'Text'
          - label: 'Content'
            name: 'content'
            widget: 'markdown'
            required: false
      - label: 'Map View'
        name: 'MapView'
        widget: 'object'
        fields:
          - label: 'Type'
            name: 'type'
            widget: 'hidden'
            default: 'MapView'
          - label: 'Map View'
            name: 'mapView'
            widget: 'select'
            options: ['view_1', 'view_2', 'view_3', 'view_4']
            required: true
      - label: 'Spacer'
        name: 'Spacer'
        widget: 'object'
        fields:
          - label: 'Type'
            name: 'type'
            widget: 'hidden'
            default: 'Spacer'
          - label: 'Desktop Height'
            name: 'desktop'
            widget: 'string'
            required: false
          - label: 'Mobile Height'
            name: 'mobile'
            widget: 'string'
            required: false
