session: &session
  label: 'Sessão'
  name: 'Session'
  summary: 'ID: {{fields.id}}'
  widget: 'object'
  fields:
    - label: 'ID'
      name: 'id'
      widget: 'string'
      required: true
    - label: 'Components'
      name: 'components'
      widget: 'list'
      required: false
      types:
        - *group
        - *cta
        - *map
