session: &session
  label: 'Session'
  name: 'Session'
  widget: 'object'
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'Session'
    - label: 'ID'
      name: 'id'
      widget: 'string'
      required: false
    - label: 'Components'
      name: 'components'
      widget: 'list'
      required: false
      types:
        - *group
        - *cta
        - *map
