components:
  -group: &group
    label: 'Group'
    name: 'group'
    widget: 'object'
    collapsed: true
    summary: 'Group - {{fields.layout}}'
    fields:
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'Group' }
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'select',
          options: ['default', 'media', 'text', 'text-bigger'],
          default: 'default',
        }
      - {
          label: 'Cor do Texto',
          name: 'txtColor',
          widget: 'color',
          required: false,
          enableAlpha: true,
        }
      - {
          label: 'Cor de Fundo',
          name: 'bgColor',
          widget: 'color',
          required: false,
          enableAlpha: true,
        }
      - {
          label: 'Imagem de Fundo',
          name: 'backgroundImage',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Overlay',
          name: 'overlay',
          widget: 'select',
          options: ['light', 'dark'],
          required: false,
        }
      - {
          label: 'Padding Superior',
          name: 'paddingTop',
          widget: 'boolean',
          required: false,
        }
      - {
          label: 'Padding Inferior',
          name: 'paddingBottom',
          widget: 'boolean',
          required: false,
        }
      - label: 'Componentes Filhos'
        name: 'components'
        widget: 'list'
        collapsed: true
        required: false
